// src/utils/mockData.js
// Realistic data for MoveSmart Ahmedabad Relocation Marketplace demo.
// Conforms to Design.md §2 color-semantic codes and database.md structure.

export const LOCALITIES = [
  {
    id: 'vastrapur',
    name: 'Vastrapur',
    description: 'Sought-after residential hub with vast lake park, top tier educational institutes, and premium shopping options.',
    overallScore: 92,
    commuteScore: 88,
    safetyScore: 95,
    schoolsScore: 94,
    costScore: 78,
    greeneryScore: 90,
    confidenceScore: 96,
    coordinates: { lat: 23.035, lng: 72.528 },
    pros: ['Excellent walkability around Lake', 'Close to IIMA & top schools', 'High safety rating'],
    cons: ['Frequent traffic during rush hour', 'Higher rent compared to SG Highway'],
    rentRange: '₹22,000 - ₹45,000',
    crimeRate: 'Very Low (0.4/1000)',
    schools: ['Ahmedabad International School', 'Shanti Asiatic School'],
    hospitals: ['Sanjivani Super Speciality Hospital', 'Sal Hospital'],
  },
  {
    id: 'satellite',
    name: 'Satellite',
    description: 'Established upmarket neighborhood with rich amenity networks, quiet tree-lined lanes, and excellent connectivity.',
    overallScore: 90,
    commuteScore: 92,
    safetyScore: 91,
    schoolsScore: 89,
    costScore: 70,
    greeneryScore: 85,
    confidenceScore: 94,
    coordinates: { lat: 23.030, lng: 72.518 },
    pros: ['Metro connectivity nearby', 'Dense network of high-street retail', 'Reliable power/water grid'],
    cons: ['Premium price point', 'Limited new constructions'],
    rentRange: '₹25,000 - ₹55,000',
    crimeRate: 'Low (0.6/1000)',
    schools: ['Satellite School for Children', 'Udgam School for Children'],
    hospitals: ['Shalby Hospitals', 'Rajasthan Hospital'],
  },
  {
    id: 'bodakdev',
    name: 'Bodakdev',
    description: 'Premium luxury zone housing upscale corporate executives, offering calm streets, elite clubs, and gourmet dining.',
    overallScore: 89,
    commuteScore: 85,
    safetyScore: 96,
    schoolsScore: 90,
    costScore: 60,
    greeneryScore: 88,
    confidenceScore: 92,
    coordinates: { lat: 23.039, lng: 72.510 },
    pros: ['Elite residential community', 'Low noise levels', 'Ultra-premium property finishes'],
    cons: ['Very high deposit requirements', 'Requires driving for basic groceries'],
    rentRange: '₹30,000 - ₹75,000',
    crimeRate: 'Very Low (0.3/1000)',
    schools: ['The Riverside School', 'Zydus School for Excellence'],
    hospitals: ['Zydus Hospital', 'CIMS Hospital'],
  },
  {
    id: 'thaltej',
    name: 'Thaltej',
    description: 'Serene suburb merging quiet residential blocks with high-growth office zones, appealing to IT professionals.',
    overallScore: 86,
    commuteScore: 87,
    safetyScore: 89,
    schoolsScore: 85,
    costScore: 82,
    greeneryScore: 84,
    confidenceScore: 89,
    coordinates: { lat: 23.050, lng: 72.502 },
    pros: ['Thaltej Metro Station access', 'Spacious layouts', 'Reasonable deposit conditions'],
    cons: ['Construction dust in active pockets', 'Water hardness is higher'],
    rentRange: '₹18,000 - ₹38,000',
    crimeRate: 'Low (0.8/1000)',
    schools: ['Anand Niketan School', 'EuroSchool'],
    hospitals: ['Sterling Hospital', 'HCG Cancer Centre'],
  },
  {
    id: 'prahladnagar',
    name: 'Prahladnagar',
    description: 'Planned commercial and high-density residential zone featuring a popular corporate garden park and high walkability.',
    overallScore: 88,
    commuteScore: 90,
    safetyScore: 92,
    schoolsScore: 87,
    costScore: 75,
    greeneryScore: 80,
    confidenceScore: 91,
    coordinates: { lat: 23.012, lng: 72.507 },
    pros: ['Walk-to-work culture potential', 'Prahladnagar Garden nearby', 'Excellent food-street options'],
    cons: ['Street parking is highly congested', 'Commercial noise during day'],
    rentRange: '₹20,000 - ₹42,000',
    crimeRate: 'Low (0.5/1000)',
    schools: ['D.A.V. International School', 'DPS Bopal (Close bus route)'],
    hospitals: ['Sola Civil Hospital (Access)', 'Kalyan Hospital'],
  },
  {
    id: 'gota',
    name: 'Gota',
    description: 'Affordable modern development cluster along SG Highway, highly popular with young student and tech relocators.',
    overallScore: 81,
    commuteScore: 75,
    safetyScore: 85,
    schoolsScore: 80,
    costScore: 95,
    greeneryScore: 72,
    confidenceScore: 85,
    coordinates: { lat: 23.098, lng: 72.531 },
    pros: ['Highly affordable rental options', 'New high-rise complexes', 'Proximity to SG Highway corridor'],
    cons: ['Longer commute to downtown', 'Public transit is sparse'],
    rentRange: '₹12,000 - ₹25,000',
    crimeRate: 'Moderate (1.1/1000)',
    schools: ['GEMS Genesis School', 'Nirma University (Campus schools)'],
    hospitals: ['Lifeline Multispecialty Hospital', 'KD Hospital'],
  }
];

export const LISTINGS = [
  {
    id: 'lst-1',
    title: 'Modern 3 BHK in Vastrapur Heights',
    locality: 'Vastrapur',
    bhk: 3,
    bathrooms: 3,
    sizeSqFt: 1750,
    dealType: 'rent',
    price: 34000,
    predictedPrice: 32500,
    predictedDiff: 4.6, // % over-predicted
    trustScore: 96,
    isSuspicious: false,
    ownerName: 'Rajesh Patel',
    phoneExposed: false,
    photos: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&auto=format&fit=crop&q=60',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&auto=format&fit=crop&q=60'
    ],
    features: ['Modular Kitchen', 'Lake View Balcony', '24/7 Security', 'Gym Access'],
    schoolDistance: 0.6,
    hospitalDistance: 0.9,
    commuteOffice: 15,
    isVerified: true,
    addedOn: '2026-07-28',
  },
  {
    id: 'lst-2',
    title: 'Luxury 4 BHK Penthouse at Bodakdev Vista',
    locality: 'Bodakdev',
    bhk: 4,
    bathrooms: 4,
    sizeSqFt: 3100,
    dealType: 'rent',
    price: 65000,
    predictedPrice: 66200,
    predictedDiff: -1.8,
    trustScore: 98,
    isSuspicious: false,
    ownerName: 'Vikram Shah',
    phoneExposed: false,
    photos: [
      'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=800&auto=format&fit=crop&q=60',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&auto=format&fit=crop&q=60'
    ],
    features: ['Private Terrace', 'Jacuzzi', 'Clubhouse Access', '3 Reserved Parking'],
    schoolDistance: 0.4,
    hospitalDistance: 1.2,
    commuteOffice: 12,
    isVerified: true,
    addedOn: '2026-07-30',
  },
  {
    id: 'lst-3',
    title: 'Cozy 2 BHK in Satellite enclave',
    locality: 'Satellite',
    bhk: 2,
    bathrooms: 2,
    sizeSqFt: 1100,
    dealType: 'rent',
    price: 24000,
    predictedPrice: 24500,
    predictedDiff: -2.0,
    trustScore: 92,
    isSuspicious: false,
    ownerName: 'Amit Trivedi',
    phoneExposed: false,
    photos: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&auto=format&fit=crop&q=60'
    ],
    features: ['Near Metro Station', 'Fully Furnished', 'Gated Community'],
    schoolDistance: 0.9,
    hospitalDistance: 0.5,
    commuteOffice: 18,
    isVerified: true,
    addedOn: '2026-08-01',
  },
  {
    id: 'lst-4',
    title: 'High-rise 3 BHK near Thaltej Metro',
    locality: 'Thaltej',
    bhk: 3,
    bathrooms: 3,
    sizeSqFt: 1600,
    dealType: 'rent',
    price: 31000,
    predictedPrice: 30000,
    predictedDiff: 3.3,
    trustScore: 89,
    isSuspicious: false,
    ownerName: 'Nisha Mehta',
    phoneExposed: false,
    photos: [
      'https://images.unsplash.com/photo-1560185007-c5ca9d2c014d?w=800&auto=format&fit=crop&q=60'
    ],
    features: ['Metro Walkable', 'Gas Pipeline', 'High Speed Elevators'],
    schoolDistance: 1.1,
    hospitalDistance: 0.7,
    commuteOffice: 20,
    isVerified: true,
    addedOn: '2026-07-25',
  },
  {
    id: 'lst-5',
    title: 'Furnished 3 BHK in Prahladnagar Corporate park',
    locality: 'Prahladnagar',
    bhk: 3,
    bathrooms: 2,
    sizeSqFt: 1450,
    dealType: 'rent',
    price: 28000,
    predictedPrice: 28200,
    predictedDiff: -0.7,
    trustScore: 94,
    isSuspicious: false,
    ownerName: 'Sanjay Rawal',
    phoneExposed: false,
    photos: [
      'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800&auto=format&fit=crop&q=60'
    ],
    features: ['Walk to Corporate garden', 'Modular Kitchen', 'Power Backup'],
    schoolDistance: 0.7,
    hospitalDistance: 1.4,
    commuteOffice: 8,
    isVerified: true,
    addedOn: '2026-08-02',
  },
  {
    id: 'lst-6',
    title: 'Budget 2 BHK Apartment in Gota Complex',
    locality: 'Gota',
    bhk: 2,
    bathrooms: 2,
    sizeSqFt: 980,
    dealType: 'rent',
    price: 14000,
    predictedPrice: 15500,
    predictedDiff: -9.6, // bargain potential
    trustScore: 86,
    isSuspicious: false,
    ownerName: 'Dharmesh Vyas',
    phoneExposed: false,
    photos: [
      'https://images.unsplash.com/photo-1505691938895-1758d7feb511?w=800&auto=format&fit=crop&q=60'
    ],
    features: ['Super Affordable', 'Parking Included', 'Low Maintenance'],
    schoolDistance: 1.5,
    hospitalDistance: 2.2,
    commuteOffice: 32,
    isVerified: true,
    addedOn: '2026-07-29',
  },
  {
    id: 'lst-7',
    title: 'Unusually Low Price 3 BHK - Suspicious Offer',
    locality: 'Satellite',
    bhk: 3,
    bathrooms: 3,
    sizeSqFt: 1800,
    dealType: 'rent',
    price: 12000, // suspicious low for Satellite
    predictedPrice: 32000,
    predictedDiff: -62.5,
    trustScore: 42,
    isSuspicious: true, // Flagged by Isolation Forest
    ownerName: 'Unknown Broker',
    phoneExposed: false,
    photos: [
      'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=800&auto=format&fit=crop&q=60'
    ],
    features: ['Immediate move-in', 'No documentation'],
    schoolDistance: 0.8,
    hospitalDistance: 1.1,
    commuteOffice: 16,
    isVerified: false,
    addedOn: '2026-08-01',
  },
  {
    id: 'lst-8',
    title: 'Premium Villa at Thaltej Orchard',
    locality: 'Thaltej',
    bhk: 5,
    bathrooms: 5,
    sizeSqFt: 4200,
    dealType: 'buy',
    price: 24000000, // 2.4 Cr
    predictedPrice: 24200000,
    predictedDiff: -0.8,
    trustScore: 97,
    isSuspicious: false,
    ownerName: 'Harsh Vardhan',
    phoneExposed: false,
    photos: [
      'https://images.unsplash.com/photo-1613977257363-707ba9348227?w=800&auto=format&fit=crop&q=60',
      'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&auto=format&fit=crop&q=60'
    ],
    features: ['Private Garden', 'Private Pool', 'Luxury Finish', 'Servant Quarters'],
    schoolDistance: 0.8,
    hospitalDistance: 1.5,
    commuteOffice: 22,
    isVerified: true,
    addedOn: '2026-07-26',
  }
];

export const COST_OF_LIVING = {
  vastrapur: { rent: 30000, transport: 4000, food: 9000, utilities: 4500, shopping: 7000 },
  satellite: { rent: 35000, transport: 3500, food: 10000, utilities: 5000, shopping: 8500 },
  bodakdev: { rent: 50000, transport: 5000, food: 14000, utilities: 6500, shopping: 12000 },
  thaltej: { rent: 26000, transport: 4500, food: 8500, utilities: 4000, shopping: 6500 },
  prahladnagar: { rent: 28000, transport: 3000, food: 9500, utilities: 4800, shopping: 8000 },
  gota: { rent: 16000, transport: 6000, food: 6500, utilities: 3500, shopping: 4500 }
};

export const MOCK_NOTIFICATIONS = [
  {
    id: 'n-1',
    category: 'price',
    title: 'Price Drop Alert',
    message: 'A listing in Satellite matching your filters dropped rent by ₹2,000.',
    time: '2 hours ago',
    unread: true,
  },
  {
    id: 'n-2',
    category: 'commute',
    title: 'Metro Schedule Update',
    message: 'New East-West corridor frequency increased — Thaltej to SG Highway commute times decreased.',
    time: '5 hours ago',
    unread: true,
  },
  {
    id: 'n-3',
    category: 'system',
    title: 'AI Report Ready',
    message: 'Your custom relocation report for Prahladnagar is ready to download.',
    time: '1 day ago',
    unread: false,
  },
  {
    id: 'n-4',
    category: 'listings',
    title: 'New Match Approved',
    message: 'Admin approved a new 3 BHK in Vastrapur Heights that fits your checklist.',
    time: '2 days ago',
    unread: false,
  }
];

export const COMMUTE_DATA = {
  vastrapur: { drive: 15, metro: 12, walk: 42, co2: 2.1 },
  satellite: { drive: 18, metro: 10, walk: 48, co2: 2.4 },
  bodakdev: { drive: 12, metro: 15, walk: 35, co2: 1.8 },
  thaltej: { drive: 20, metro: 14, walk: 55, co2: 2.7 },
  prahladnagar: { drive: 8, metro: 16, walk: 25, co2: 1.2 },
  gota: { drive: 32, metro: 28, walk: 90, co2: 4.2 }
};

export const MOCK_CHATS = [
  { sender: 'ai', text: "Hello! I am your MoveSmart AI Relocation assistant. I can recommend neighborhoods in Ahmedabad, analyze commutes, estimate your cost of living, and flag listing anomalies. Try asking me:\n\n* *'Which area is best for access to top schools and has a safe atmosphere?'*\n* *'What would my monthly budget look like in Bodakdev compared to Gota?'*\n* *'Can you summarize the amenities near Vastrapur Heights?'*" }
];
